services:
  postgres:
    image: postgres:15
    container_name: fitness_db
    environment:
      POSTGRES_DB: FitnessTrackerDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../main
      dockerfile: Dockerfile
    container_name: fitness_backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/FitnessTrackerDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres


volumes:
  postgres_data:
